version: '3.4'

services:
  api:
    environment:
      - AWS_REGION=ap-southeast-1
      - AWS_PROFILE=default
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${USERPROFILE}/.aws:/root/.aws:ro
